# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Newsinfo',
            fields=[
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('img_path', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'newsinfo',
            },
        ),
        migrations.CreateModel(
            name='Usercf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'usercf',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('psw', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'weights',
            },
        ),
    ]
